Repository boostcamp-2020/IssueTracker-37, pull requests merged in 2020-11, with the labels that each got.

#67 [J118] 댓글삭제, 해당이슈 milestone 삭제, 해당이슈 assignee 등록 API
  server/src/api/index.js
  server/src/api/issue/issue-controller.js
  server/src/api/issue/issue-router.js
  server/src/sequelize/models/comment-model.js
  server/src/sequelize/models/issue-model.js
  server/src/services/issue-service.js
Labels: BE

#68 [J098] 이슈 조회, 라벨등록, Assignee 제거 API 구현
  server/src/api/issue/issue-controller.js
  server/src/api/issue/issue-router.js
  server/src/api/user/user-controller.js
  server/src/sequelize/extra-setup.js
  server/src/sequelize/index.js
  server/src/sequelize/models/issue-model.js
  server/src/services/issue-service.js
Labels: BE

#71 [J059] 이슈 마일스톤 등록, 이슈에 라벨삭제, 전체이슈조회
  server/.eslintrc
  server/package-lock.json
  server/package.json
  server/src/api/issue/issue-controller.js
  server/src/api/issue/issue-router.js
  server/src/sequelize/models/issue-model.js
  server/src/services/issue-service.js
Labels: BE

#76 [J118] passport jwt, local 전략, signin 기능 구현, atomic design 패턴 일부구현
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/atoms/Button/index.js
  client/src/components/atoms/Input/index.js
  client/src/components/atoms/Span/index.js
  client/src/components/molecules/ImgTitle/index.js
  client/src/components/molecules/ImgTitle/style.js
  client/src/components/molecules/ImgTitleCount/index.js
  client/src/components/molecules/ImgTitleCount/style.js
  client/src/components/molecules/SearchBox/index.js
  client/src/components/molecules/SearchBox/style.js
  client/src/components/organisms/Header/index.js
  client/src/components/organisms/Header/style.js
  client/src/hoc/Auth.js
  client/src/pages/Main.js
  client/webpack.config.js
  server/src/api/user/user-routes.js
  server/src/middlewares/auth.js
  server/src/middlewares/passport/jwt.js
  server/src/middlewares/passport/local.js
  server/src/sequelize/models/issue-model.js
  server/src/services/issue-service.js
Labels: BE

#79 [J149] 이슈 등록 API 구현 마무리, GitHub Passport 전략 이슈 수정
  client/public/img/Issues.png
  client/public/img/closed_issue.png
  client/public/img/imoji.png
  client/public/img/label.png
  client/public/img/milestone.png
  client/public/img/opened_issue.png
  client/public/img/search.png
  client/public/img/setting.png
  server/package.json
  server/src/api/issue/issue-controller.js
  server/src/middlewares/passport/github.js
  server/src/services/issue-service.js
Labels: BE

#75 [J059] 해당이슈 마일스톤등록 로직수정
  server/src/api/issue/issue-controller.js
  server/src/api/issue/issue-routes.js
  server/src/sequelize/models/comment-model.js
  server/src/sequelize/models/issue-model.js
  server/src/sequelize/models/milestone-model.js
  server/src/services/issue-service.js
Labels: BE

#82 [J098, J149] Navbar, IssueListHeader 구현
  client/src/components/atoms/DropdownItem/index.js
  client/src/components/atoms/DropdownItem/style.js
  client/src/components/atoms/DropdownTitle/index.js
  client/src/components/atoms/DropdownTitle/style.js
  client/src/components/molecules/Dropdown/index.js
  client/src/components/molecules/Dropdown/style.js
  client/src/components/molecules/ImgTitleCount/index.js
  client/src/components/molecules/ImgTitleCount/style.js
  client/src/components/molecules/IssueListHeader/index.js
  client/src/components/molecules/IssueListHeader/style.js
  client/src/components/molecules/NavButton/index.js
  client/src/components/molecules/NavButton/style.js
  client/src/components/molecules/SearchBox/index.js
  client/src/components/molecules/SearchBox/style.js
  client/src/components/organisms/Navbar/index.js
  client/src/components/organisms/Navbar/style.js
  client/src/pages/Main.js
Labels: FE

#84 [J098, J149] SVG 컴포넌트 추가
  client/public/img/svgs.js
  client/src/components/atoms/SVG/index.js
Labels: FE

#91 [J118] label 조회, milestone 삭제 API 구현
  server/src/api/index.js
  server/src/api/label/label-controller.js
  server/src/api/label/label-routes.js
  server/src/api/milestone/milestone-controller.js
  server/src/api/milestone/milestone-routes.js
  server/src/sequelize/models/label-model.js
  server/src/sequelize/models/milestone-model.js
  server/src/services/label-service.js
  server/src/services/milestone-service.js
Labels: BE

#93 [J098] 마일스톤 전체조회, 라벨 수정 API 구현
  server/src/api/index.js
  server/src/api/issue/issue-controller.js
  server/src/api/label/label-controller.js
  server/src/api/label/label-routes.js
  server/src/api/milestone/milestone-controller.js
  server/src/api/milestone/milestone-routes.js
  server/src/sequelize/models/comment-model.js
  server/src/sequelize/models/issue-model.js
  server/src/sequelize/models/label-model.js
  server/src/sequelize/models/milestone-model.js
  server/src/services/issue-service.js
  server/src/services/label-service.js
  server/src/services/milestone-service.js
Labels: BE

#94 [J149] milestone 생성 API, label 삭제 API 구현, sequelize 설정 변경
  server/src/api/index.js
  server/src/api/label/label-controller.js
  server/src/api/label/label-routes.js
  server/src/api/milestone/milestone-controller.js
  server/src/api/milestone/milestone-routes.js
  server/src/sequelize/config/config.js
  server/src/sequelize/models/label-model.js
  server/src/sequelize/models/milestone-model.js
  server/src/services/label-service.js
  server/src/services/milestone-service.js
Labels: BE

#101 [J059, J118] Issue 생성 페이지 구현
  client/src/App.js
  client/src/components/IssueForm/index.js
  client/src/components/IssueForm/style.js
  client/src/components/IssueOption/index.js
  client/src/components/IssueOption/style.js
  client/src/components/atoms/Button/index.js
  client/src/components/atoms/Button/style.js
  client/src/components/atoms/Img/style.js
  client/src/components/atoms/SVG/index.js
  client/src/components/atoms/Span/index.js
  client/src/components/atoms/Span/style.js
  client/src/components/atoms/TextArea/index.js
  client/src/components/atoms/_DropdownItem/index.js
  client/src/components/atoms/_DropdownItem/style.js
  client/src/components/molecules/DropdownButton/index.js
  client/src/components/molecules/DropdownButton/style.js
  client/src/pages/CreateIssue/index.js
  client/src/pages/CreateIssue/style.js
  client/webpack.config.js
  server/src/api/label/label-controller.js
  server/src/api/milestone/milestone-controller.js
  server/src/api/user/user-controller.js
  server/src/services/label-service.js
Labels: FE

#99 [J098, J149] Label Page, DropdownButton Molecule 구현
  client/public/img/svgs.js
  client/src/App.js
  client/src/components/atoms/IssueLabel/index.js
  client/src/components/atoms/Label/index.js
  client/src/components/atoms/SVG/index.js
  client/src/components/molecules/DropdownButton/index.js
  client/src/components/molecules/DropdownButton/style.js
  client/src/components/molecules/ImgTitleCount/index.js
  client/src/components/molecules/ImgTitleCount/style.js
  client/src/components/molecules/IssueListHeader/index.js
  client/src/components/molecules/IssueListHeader/style.js
  client/src/components/molecules/LabelForm/index.js
  client/src/components/molecules/LabelForm/style.js
  client/src/components/molecules/LabelItem/index.js
  client/src/components/molecules/LabelItem/style.js
  client/src/components/molecules/NavButton/index.js
  client/src/components/molecules/NavButton/style.js
  client/src/components/organisms/LabelContent/index.js
  client/src/components/organisms/LabelContent/style.js
  client/src/components/organisms/Navbar/index.js
  client/src/components/organisms/SimpleNavbar/index.js
  client/src/components/organisms/SimpleNavbar/style.js
  client/src/lib/axios.js
  client/src/pages/Label/Template/index.js
  client/src/pages/Label/Template/style.js
  client/src/pages/Label/index.js
  client/src/pages/Main/index.js
  client/src/pages/Milestone/Template/index.js
  client/src/pages/Milestone/Template/style.js
  client/src/pages/Milestone/index.js
  client/src/utils/color.js
  server/src/api/label/label-controller.js
  server/src/sequelize/models/label-model.js
Labels: FE

#103 [J098] 마일스톤 페이지 구현
  client/public/img/svgs.js
  client/src/components/molecules/ImgTitleCount/index.js
  client/src/components/molecules/LabelForm/index.js
  client/src/components/molecules/MilestoneItem/index.js
  client/src/components/molecules/MilestoneItem/style.js
  client/src/components/molecules/ProgressBar/index.js
  client/src/components/molecules/ProgressBar/style.js
  client/src/components/organisms/LabelContent/index.js
  client/src/components/organisms/MilestoneContent/index.js
  client/src/components/organisms/MilestoneContent/style.js
  client/src/pages/Label/index.js
  client/src/pages/Milestone/Template/index.js
  client/src/pages/Milestone/index.js
  server/src/api/milestone/milestone-controller.js
  server/src/sequelize/models/milestone-model.js
  server/src/services/milestone-service.js
Labels: FE

#104 [J059, J118] 이슈 생성 페이지 구현
  client/public/index.html
  client/src/components/IssueForm/index.js
  client/src/components/IssueOption/index.js
  client/src/components/IssueOption/style.js
  client/src/components/atoms/AssigneeContent/index.js
  client/src/components/atoms/AssigneeContent/style.js
  client/src/components/atoms/LabelContent/index.js
  client/src/components/atoms/LabelContent/style.js
  client/src/components/atoms/MilestoneContent/index.js
  client/src/components/atoms/MilestoneContent/style.js
  client/src/components/atoms/ProgressBar/index.js
  client/src/components/atoms/ProgressBar/style.js
  client/src/components/atoms/_DropdownItem/index.js
  client/src/components/atoms/_DropdownItem/style.js
  client/src/components/molecules/DropdownButton/index.js
  client/src/components/molecules/DropdownButton/style.js
  client/src/components/organisms/Navbar/index.js
  client/src/hoc/useFetch.js
  client/src/pages/CreateIssue/index.js
Labels: FE

#108 [J098, J149] 마일스톤 수정, 생성 페이지 구현
  client/src/App.js
  client/src/components/atoms/TextArea/style.js
  client/src/components/molecules/LabelForm/style.js
  client/src/components/molecules/MilestoneForm/index.js
  client/src/components/molecules/MilestoneForm/style.js
  client/src/components/molecules/SubHeader/index.js
  client/src/components/molecules/SubHeader/style.js
  client/src/components/organisms/Header/index.js
  client/src/components/organisms/Header/style.js
  client/src/components/organisms/SimpleNavbar/index.js
  client/src/lib/axios.js
  client/src/pages/CreateMilestone/Template/index.js
  client/src/pages/CreateMilestone/Template/style.js
  client/src/pages/CreateMilestone/index.js
  client/src/pages/EditMilestone/Template/index.js
  client/src/pages/EditMilestone/Template/style.js
  client/src/pages/EditMilestone/index.js
  server/src/api/milestone/milestone-controller.js
  server/src/api/milestone/milestone-routes.js
  server/src/sequelize/models/milestone-model.js
  server/src/services/milestone-service.js
Labels: FE

#113 [J149] GitHub OAuth 인증 과정 Refactoring
  client/src/pages/GitHubCallbackPage/index.js
  server/package-lock.json
  server/package.json
  server/src/api/user/user-controller.js
  server/src/api/user/user-routes.js
  server/src/middlewares/auth.js
  server/src/middlewares/passport/github.js
  server/src/middlewares/passport/index.js
  server/src/oauth/github.js
Labels: BE, FE

#116 [J098, J149] 메인페이지 필터, Mark as 기능 구현
  client/src/components/atoms/CheckBox/index.js
  client/src/components/atoms/Checkbox/index.js
  client/src/components/atoms/Input/index.js
  client/src/components/atoms/_DropdownItem/index.js
  client/src/components/atoms/_DropdownItem/style.js
  client/src/components/molecules/DropdownButton/index.js
  client/src/components/molecules/DropdownButton/style.js
  client/src/components/molecules/ImgTitleCount/index.js
  client/src/components/molecules/IssueItem/index.js
  client/src/components/molecules/IssueItem/style.js
  client/src/components/molecules/IssueListHeader/index.js
  client/src/components/molecules/IssueListHeader/style.js
  client/src/components/molecules/LabelItem/index.js
  client/src/components/molecules/MilestoneForm/index.js
  client/src/components/molecules/NoneDataBox/index.js
  client/src/components/molecules/NoneDataBox/style.js
  client/src/components/molecules/SearchBox/index.js
  client/src/components/molecules/SearchBox/style.js
  client/src/components/organisms/IssueContent/index.js
  client/src/components/organisms/LabelContent/index.js
  client/src/components/organisms/MilestoneContent/index.js
  client/src/components/organisms/Navbar/index.js
  client/src/pages/CreateMilestone/index.js
  client/src/pages/EditMilestone/index.js
  client/src/pages/Label/index.js
  client/src/pages/Main/Template/style.js
  client/src/pages/Main/index.js
  client/src/pages/Milestone/Template/style.js
  client/src/pages/Milestone/index.js
  client/src/utils/filter.js
  server/src/api/issue/issue-controller.js
  server/src/api/issue/issue-routes.js
  server/src/sequelize/models/issue-model.js
  server/src/services/issue-service.js
Labels: BE, FE
