Repository boostcamp-2020/IssueTracker-37, pull requests merged in 2020-10, with the labels that each got.

#43 [J098] 회원가입 API, 페이지 구현
  client/src/pages/signupPage.js
  server/package.json
  server/src/api/index.ts
  server/src/api/user/user-controller.js
  server/src/api/user/user-controller.ts
  server/src/api/user/user-routes.js
  server/src/api/user/user-routes.ts
  server/src/services/user-service.ts
Labels: BE, FE

#42 [J118] passport local, jwt 전략 구현[작업중], bcrypt 유틸함수 구현
  server/package-lock.json
  server/package.json
  server/src/middlewares/auth.ts
  server/src/middlewares/passport.ts
  server/src/sequelize/index.ts
  server/src/utils/bcrypt.ts
  server/src/utils/server-message.ts
Labels: BE

#47 [J118] package-lock.json, index.ts 버그 수정
  .gitignore
  server/package-lock.json
  server/src/api/index.ts
Labels: bug

#48 [J098] axios 에러 해결, 환결설정 추가
  client/package.json
  client/src/pages/signupPage.js
  client/webpack.config.js
  server/src/services/user-service.ts
  server/tsconfig.json
Labels: BE, FE, bug
